config/routes.rb
Rails.application.routes.draw do

  root :to => 'videos#index'

  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'upload' => 'videos#new'

  resources :channels, only: [:index, :show]

  resources :videos, except: [:delete, :edit, :update] do
    collection do
      get 'search'
    end
    resources :comments, except: [:edit, :new, :index, :show]
  end
  resources :playlist_video_relations, only: [:create, :destroy]
  resources :subscriptions, only: [:create, :update, :destroy]

  resource :user, except: [:index, :update] do
    resources :channels
    resources :subscriptions, only: [:index]
    resources :videos, only: [:index]
    resources :playlists, only: [:index, :show, :create, :update, :destroy]
    resources :comments, except: [:edit, :new, :index, :show]
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  include Gravtastic
  gravtastic

  has_many :videos
  has_many :playlists
  has_many :channels
  has_many :subscriptions
  has_many :comments

  validates :name, presence:true
  validates :email, presence:true

  has_secure_password

  after_create :create_initial_channel
  after_create :create_initial_playlist
  def create_initial_channel
    self.channels.create(name: self.name, current: true)
  end

  def create_initial_playlist
    self.playlists.create(name: "お気に入り", playlist_type: Playlist.types[:favorite])
    self.playlists.create(name: "高く評価した動画", playlist_type: Playlist.types[:like])
    self.playlists.create(name: "低く評価した動画", playlist_type: Playlist.types[:dislike])
    self.playlists.create(name: "後で見る", playlist_type: Playlist.types[:later])
    self.playlists.create(name: "履歴", playlist_type: Playlist.types[:history])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user, except: [:create, :new]
  before_action :set_user, only: [:show, :update, :destroy, :home, :edit]

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to :root
    else
      redirect_to :root
    end
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private
    def set_user
      logger.debug(params[:format])
      unless params[:format].blank?
        logger.debug("not current_user")
        @user = User.find(params[:format])
      else
        logger.debug("current_user")
        @user = current_user
      end
    end

    def user_params
      params.require(:user).permit(:name, :email, :password, channels_attributes: [:id, :name])
    end
end

app/helpers/users_helper.rb
module UsersHelper
  THUMB_SIZE = "128x72"

  def custom_playlists_links_to(playlists)
    html = capture do
      content_tag_for :div, playlists, class: "pull-left" do |playlist|
        if playlist.videos.any?
          concat (content_tag :div, class: "image-link" do
            concat link_to image_tag(playlist.videos.first.uri_url(:thumb), size: THUMB_SIZE), [playlist.user, playlist]
          end)
          concat (content_tag :div, class: "name-link" do
            concat link_to playlist.name, [playlist.user, playlist]
          end)
        else
          no_video_link_to playlist.name
        end
      end
    end
  end

  def videos_link_to(videos)
    html = capture do
      if videos.any?
        content_tag_for :div, videos, class: "pull-left" do |video|
          concat (content_tag :div, class: "image-link" do
            concat link_to image_tag(video.uri_url(:thumb), size: THUMB_SIZE), video
          end)
          concat (content_tag :div, class: "name-link" do
            concat link_to video.title, video
          end)
        end
      else
        no_video_link_to
      end
    end
  end

  def no_video_link_to(name = "")
    html = capture do
      concat content_tag :div, "動画はありません。", class: "image-link"
      concat content_tag :div, name, class: "name-link"
    end
  end
end

app/views/users/_form.html.haml
.container
  = form_for @user, url:user_path, html: {class: "form-signin"} do |f|
    - if @user.errors.any?
      #error_explanation
        %h2= "#{pluralize(@user.errors.count, "error")} サインアップに失敗しました"
        %ul
          - @user.errors.full_messages.each do |msg|
            %li= msg

    %h2.form-signin-heading サインアップ
    .field
      = f.label :name, class: "sr-only"
      = f.text_field :name, class: "form-control", placeholder: "Name"
    .field
      = f.label :email, class: "sr-only"
      = f.email_field :email, class: "form-control", placeholder: "E-mail address"
    .field
      = f.label :password, class: "sr-only"
      = f.password_field :password, class: "form-control", placeholder: "Password"
    .actions
      = f.submit 'サインアップ', class: "btn btn-lg btn-primary btn-block"

app/views/users/_my_menu.html.haml
%ul.nav.navbar-nav.navbar-fluid
  %li.home
    = link_to "ホーム", videos_path
  %li.videos
    = link_to "動画", user_videos_path
  %li.playlists
    = link_to "再生リスト", user_playlists_path
  %li.subscriptions
    = link_to "チャンネル", user_subscriptions_path
  %li.description
    = link_to "概要", edit_user_path

app/views/users/new.html.haml
= render 'form'

app/views/users/show.html.haml
%p#notice= notice
.user-container
  .row.channel-info
    .covor-image
      = image_tag @user.gravatar_url, class: "channel-image"
    .channel-name
      %h3 #{ @user.channels.current_channel.name }
  .row.playlists
    %h3 作成した再生リスト
    = custom_playlists_links_to @user.playlists.custom_list
  .row.my-videos
    %h3 アップロードした動画
    = videos_link_to @user.videos
  .row.high-reputated-videos
    %h3 高く評価した動画
    = videos_link_to @user.playlists.like.videos
  .row.subscribed-channel
    %h3 登録チャンネル
    - @user.subscriptions.each do |subscription|
      .image-link
        = link_to image_tag(subscription.channel.videos.first.uri_url(:thumb), size: "128x72"), subscription.channel
      .name-link
        = link_to subscription.channel.name, subscription.channel