config/routes.rb
Rails.application.routes.draw do

  root :to => 'videos#index'

  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'upload' => 'videos#new'

  resources :channels, only: [:index, :show]

  resources :videos, except: [:delete, :edit, :update] do
    collection do
      get 'search'
    end
    resources :comments, except: [:edit, :new, :index, :show]
  end
  resources :playlist_video_relations, only: [:create, :destroy]
  resources :subscriptions, only: [:create, :update, :destroy]

  resource :user, except: [:index, :update] do
    resources :channels
    resources :subscriptions, only: [:index]
    resources :videos, only: [:index]
    resources :playlists, only: [:index, :show, :create, :update, :destroy]
    resources :comments, except: [:edit, :new, :index, :show]
  end
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :user
  belongs_to :channel
  
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :require_user, only:[:index, :update, :create, :destroy]
  before_action :set_subscription, only:[:update, :destroy]

  def index
    @subscriptions = current_user.subscriptions
  end

  def create
    channel = Channel.find(params[:channel])
    if current_user.channels.exists?(channel)
      redirect_to :back, notice: '自分のチャンネルは登録できません。'
    else
      @subscription = current_user.subscriptions.build(channel: channel)
      @subscription.save
      redirect_to :back
    end
  end

  def destroy
    @subscription.destroy
    redirect_to :back
  end

  private
    def set_subscription
      @subscription = Subscription.find(params[:id])
    end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/index.html.haml
%p#notice= notice

.container
  .row.my-menu.center-block
    = render partial: "users/my_menu"
  .row.subscriptions
    %h3 登録チャンネル
  .row.list
    - if @subscriptions.any?
      %ul.nav.navbar-nav
        - @subscriptions.each do |subscription|
          %li.list-inline
            .name
              名前 #{subscription.channel.name}
            .thumbnail
              = link_to image_tag(subscription.channel.videos.first.uri_url(:thumb)), channel_path(subscription.channel)
    - else
      登録したチャンネルはありません。