config/routes.rb
Rails.application.routes.draw do

  root :to => 'videos#index'

  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'upload' => 'videos#new'

  resources :channels, only: [:index, :show]

  resources :videos, except: [:delete, :edit, :update] do
    collection do
      get 'search'
    end
    resources :comments, except: [:edit, :new, :index, :show]
  end
  resources :playlist_video_relations, only: [:create, :destroy]
  resources :subscriptions, only: [:create, :update, :destroy]

  resource :user, except: [:index, :update] do
    resources :channels
    resources :subscriptions, only: [:index]
    resources :videos, only: [:index]
    resources :playlists, only: [:index, :show, :create, :update, :destroy]
    resources :comments, except: [:edit, :new, :index, :show]
  end
end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  belongs_to :user
  has_many :videos, through: :playlist_video_relations
  has_many :playlist_video_relations

  enum type: [:like, :dislike, :later, :favorite, :history, :other]

  def build_relation(video)
    self.playlist_video_relations.build(video: video)
  end

  def video_relation(video)
    self.playlist_video_relations.where(video: video).first
  end

  def already?(video)
    self.playlist_video_relations.where(video: video).exists?
  end

  def self.operatable_list
    self.where(playlist_type: [2,3,5])
  end

  def self.custom_list
    self.where(playlist_type: [2,5])
  end

  def self.get(playlist_type)
    self.where(playlist_type: playlist_type).first
  end

  def self.like
    self.where(playlist_type: Playlist.types[:like]).first
  end

  def self.dislike
    return self.where(playlist_type: Playlist.types[:dislike]).first
  end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_action :require_user
  before_action :set_playlist, only: [:show, :destroy]

  def index
    @playlists = current_user.playlists.all
  end

  def show
  end

  def create
    @playlist = Playlist.new(playlist_params)
    @playlist.save
    redirect_to :back
  end

  def destroy
    @playlist.destroy
    redirect_to :back
  end

  private
    def set_playlist
      @playlist = current_user.playlists.find(params[:format])
    end

    def playlist_params
      params.require(:playlist).permit(:name, :user_id, :playlist_type)
    end
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/views/playlists/index.haml
%p#notice= notice
.container
  .row.my-menu.center-block
    = render partial: "users/my_menu"
  %h3 再生リスト
  .row.playlists
    %ul.list-inline
      - current_user.playlists.each do |playlist|
        %li
          .name
            = playlist.name
          .thumbnail
            - if playlist.videos.any?
              = link_to image_tag(playlist.videos.first.uri_url(:thumb)), user_playlist_path(playlist)
            - else
              %h5 動画はありません

app/views/playlists/show.html.haml
%p#notice=notice
.container
  .row.playlist
    .col-md-8
      - @playlist.videos.each_with_index do |video, index|
        = video_tag video.uri, controls:true, size:"730x408", class:"playlist-video", id: index
    .col-md-4.title-list
      .playlist-name
        %h5 #{ @playlist.name }
        %small
          #{ @playlist.user.channels.current_channel.name }
          1 / #{ @playlist.videos.count } 本の動画
      - @playlist.videos.each do |video|
        .video-info
          .image.pull-left
            = link_to image_tag(video.uri_url(:thumb), size: "64x36"), video
          .description
            .title
              = link_to video.title, video

.container.main-content
  .col-md-8.main
    = render "videos/video_info", video: @playlist.videos.first
  .col-md-4.candidates
    = render "videos/candidates", videos: Video.recommends