config/routes.rb
Rails.application.routes.draw do

  root :to => 'videos#index'

  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'upload' => 'videos#new'

  resources :channels, only: [:index, :show]

  resources :videos, except: [:delete, :edit, :update] do
    collection do
      get 'search'
    end
    resources :comments, except: [:edit, :new, :index, :show]
  end
  resources :playlist_video_relations, only: [:create, :destroy]
  resources :subscriptions, only: [:create, :update, :destroy]

  resource :user, except: [:index, :update] do
    resources :channels
    resources :subscriptions, only: [:index]
    resources :videos, only: [:index]
    resources :playlists, only: [:index, :show, :create, :update, :destroy]
    resources :comments, except: [:edit, :new, :index, :show]
  end
end

app/views/layouts/application.html.haml
!!!5
%html
%head
  %title Toutube
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags
%body

%header
  %nav
    .container-fluid
      .video-menu.navbar-header.pull-left
        = side_bar_toggle_button_to
      .logo-top-link.pull-left
        = link_to "not-visible-caption", videos_path, class: "home-button navbar-brand"
      .search-bar.pull-left
        = search_form_for
      %ul.user-menu.list-inline.navbar-right
        - if current_user
          %li.upload.hidden-xs
            = link_to "アップロード", new_video_path
          %li.user-icon
            = image_tag current_user.gravatar_url, size: "50x50"
        - else
          %li.login.btn
            = link_to 'ログイン', login_path
          %li.signup.btn
            = link_to "サインアップ", signup_path
      - if current_user
        .user-description
          .email
            = current_user.email
          .channel
            .image.pull-left
              = image_tag current_user.gravatar_url, size: "50x50"
            .channel-info
              .name
                = current_user.channels.current_channel.name
              .subscriptions
                チャンネル登録者数 #{ current_user.channels.current_channel.subscriptions.count } 人
            .logout
              = link_to "ログアウト", logout_path, method: :delete


.body
  .container-fluid
    .left-side-menu
      - unless current_user
        %nav.navbar
          %ul.nav.nav-stacked
            %li.home
              .glyphicon.glyphicon-home
                = link_to "ホーム", videos_path

          .category
            BEST OF ITOTUBE

          %ul.nav.navbar-stacked
            %li.popularity
              .glyphicon.glyphicon-star-empty
              %span ito-tubeで人気
            %li.allchannnels
              .glyphicon.glyphicon-plus-sign
              %span チャンネル一覧
            %li.login
              = link_to 'ログイン', login_path, class:"btn-xs btn-primary"
      - else
        %nav.navbar
          %ul.nav.nav-stacked
            %li.home
              .glyphicon.glyphicon-home
                = link_to "ホーム", videos_path
            %li.mychannel
              .glyphicon.glyphicon-user.pull-left
              .link
                = link_to "マイチャンネル", current_user
            %li.subscriptions
              .glyphicon.glyphicon-inbox
                = link_to "登録チャンネル", current_user
            %li.history
              .glyphicon.glyphicon-hourglass
                = link_to "履歴", current_user, query: Playlist.types[:history]
            %li.later
              .glyphicon.glyphicon-dashboard
                = link_to "後で見る", current_user, query: Playlist.types[:later]

          .playlist
            再生リスト
            %ul.nav.nav-stacked
              - current_user.playlists.operatable_list.each do |playlist|
                %li.playlist-item
                  .glyphicon.glyphicon-menu-hamburger.pull-left
                  .link
                    = link_to playlist.name, current_user

          .subscriptions
            = link_to "登録チャンネル", current_user

          %ul.nav.nav-stacked
            - current_user.subscriptions.each do |subscription|
              %li.channel-subscriptions
                .channel
                  = image_tag subscription.channel.user.gravatar_url, size: "16x16"
                  = link_to subscription.channel.name, subscription.channel

          %ul.nav.navbar-stacked
            %li.allchannnels
              .glyphicon.glyphicon-plus-sign.pull-left
              .link
                = link_to "チャンネル一覧", channels_path
            %li.management_subscriptions
              .glyphicon.glyphicon-cog.pull-left
              .link
                = link_to "登録リストを管理", channels_path
    .contents
      = yield